### ISSUE TITLE
Photography section out of date

### ISSUE THREAD

**Issue by schlenks** [valeriangalliat/blog#5]
I was reviewing the [photography section](https://photography.codejam.info/) on your site and noticed that you haven't updated with any new photos in almost 6 months.

**Comment by valeriangalliat** [comment]
Hahaha Doug, I sure wasn't expecting that issue here :D you are absolutely right I haven't updated the photography part in a while, mostly because I haven't been taking that many pictures during the winter as I was mostly [skiing](https://www.youtube.com/watch?v=nEz1yXly-Uk), some of it I did [shoot](https://www.youtube.com/watch?v=GTG2RmgJe8c) on [GoPro](https://www.youtube.com/watch?v=3hj3r9ZNh3Q) though.

But I was indeed also lagging on a [couple](https://photography.codejam.info/2020/2020-02-05-backcountry-tremblant.html) shooting ["sessions"](https://photography.codejam.info/2020/2020-05-20-ouareau-summit.html) on the website so I've just pushed that long due update. ;)

As you can see I've been more into the motion picture side of things rather than still pictures :joy: so you can checkout the stuff I'm publishing [there](https://www.youtube.com/channel/UCzpErreSO-Fv2oY5t-YXvRw) instead. \o/

Cheers! 🥃
